package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0



/**
 * Boleto generated by hbm2java
 */
public class Boleto  {


     private String idBoleto;
     private String idPasajero;
     private String idViaje;
     private String valorPagar;
     private String boletos;

    public Boleto() {
    }

    public String getIdBoleto() {
        return idBoleto;
    }

    public void setIdBoleto(String idBoleto) {
        this.idBoleto = idBoleto;
    }

    public String getIdPasajero() {
        return idPasajero;
    }

    public void setIdPasajero(String idPasajero) {
        this.idPasajero = idPasajero;
    }

    public String getIdViaje() {
        return idViaje;
    }

    public void setIdViaje(String idViaje) {
        this.idViaje = idViaje;
    }

    public String getValorPagar() {
        return valorPagar;
    }

    public void setValorPagar(String valorPagar) {
        this.valorPagar = valorPagar;
    }

    public String getBoletos() {
        return boletos;
    }

    public void setBoletos(String boletos) {
        this.boletos = boletos;
    }


}


