package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad {


     private String idCiudad;
     private String nombre;
     

    public Ciudad() {
    }

    public String getIdCiudad() {
        return idCiudad;
    }

    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }



}


