package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0



/**
 * Color generated by hbm2java
 */
public class Color   {


     private String idColor;
     private String nombre;
    

    public Color() {
    }

	
    public Color(String idColor) {
        this.idColor = idColor;
   
   

}

    public String getIdColor() {
        return idColor;
    }

    public void setIdColor(String idColor) {
        this.idColor = idColor;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
