package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0


/**
 * Marca generated by hbm2java
 */
public class Marca {


     private String idMarca;
     private String nombre;
    

    public Marca() {
    }

	
    public Marca(String idMarca) {
        this.idMarca = idMarca;
    }

    public String getIdMarca() {
        return idMarca;
    }

    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   

}


