package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0




/**
 * Modelo generated by hbm2java
 */
public class Modelo   {


     private String idModelo;
     private String nombre;
     

    public Modelo() {
    }

    public String getIdModelo() {
        return idModelo;
    }

    public void setIdModelo(String idModelo) {
        this.idModelo = idModelo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


}


