package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0


/**
 * Pasajero generated by hbm2java
 */
public class Pasajero {


     private String idPasajero;
  

    public Pasajero() {
    }

    public String getIdPasajero() {
        return idPasajero;
    }

    public void setIdPasajero(String idPasajero) {
        this.idPasajero = idPasajero;
    }


}


