package proy.modelo.entidad;
// Generated 21/06/2015 10:04:22 AM by Hibernate Tools 3.6.0


/**
 * Viaje generated by hbm2java
 */
public class Viaje  {


     private String idViaje;
     private String IdCiudadSalida;
     private String idVehiculo;
     private String IdCiudadDestino;
     private String fechaViaje;
     private String horaViaje;
     private String estado;
     private String idConductor;

    public Viaje() {
    }

    public String getIdViaje() {
        return idViaje;
    }

    public void setIdViaje(String idViaje) {
        this.idViaje = idViaje;
    }

    public String getIdCiudadSalida() {
        return IdCiudadSalida;
    }

    public void setIdCiudadSalida(String IdCiudadSalida) {
        this.IdCiudadSalida = IdCiudadSalida;
    }

    public String getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    public String getIdCiudadDestino() {
        return IdCiudadDestino;
    }

    public void setIdCiudadDestino(String IdCiudadDestino) {
        this.IdCiudadDestino = IdCiudadDestino;
    }

    public String getFechaViaje() {
        return fechaViaje;
    }

    public void setFechaViaje(String fechaViaje) {
        this.fechaViaje = fechaViaje;
    }

    public String getHoraViaje() {
        return horaViaje;
    }

    public void setHoraViaje(String horaViaje) {
        this.horaViaje = horaViaje;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getIdConductor() {
        return idConductor;
    }

    public void setIdConductor(String idConductor) {
        this.idConductor = idConductor;
    }
     

  
}


